lockups, blocks, overwrite of parked pages, nested widgets, performan…
apostrophecms/apostrophe-legacy-import pull request #3
Opened 2020-09-16 17:49 UTC by boutell

…ce improvements

2020-09-16 18:45 UTC, abea approved these changes

2020-09-17 11:59 UTC, falkodev requested changes

2020-09-17 11:59 UTC, falkodev commented on README.md
> +If you already have a 2.x site with content, importing a piece type like `apostrophe-blog` like this should not unduly impact the rest of your sitem, however there is no guarantee of this. Always bac
`site` instead `sitem`?

2020-09-17 11:59 UTC, falkodev commented on index.js
> +      console.log('Conecting to legacy db');
`Connecting`

2020-09-17 12:27 UTC, falkodev approved these changes

2020-09-17 12:48 UTC, merged